### ISSUE TITLE
RuntimeError: set_wakeup_fd only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by subjoel** [OxynDev/Backup-Cord#2]
> WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/asyncio/unix_events.py", line 95, in add_signal_handler
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread of the main interpreter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/alt/python39/lib64/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/alt/python39/lib64/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/darkehld/virtualenv/verify.darkys.wtf/3.9/lib/python3.9/site-packages/discord/client.py", line 701, in run
    loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
  File "/opt/alt/python39/lib64/python3.9/asyncio/unix_events.py", line 97, in add_signal_handler
    raise RuntimeError(str(exc))
RuntimeError: set_wakeup_fd only works in main thread of the main interpreter

> ``

**Comment by OxynDev** [comment]
remove all discord libs from libs dir
and install this
pip install --force-reinstall discord.py-message-components
